version: '3.8'
services:
  mageai:
    build: . 
    container_name: mageai_container
    ports:
      - "6789:6789"
    volumes:
      - "./:/home/src"
    command: "/app/run_app.sh mage start crypto-bot"
    env_file:
      - .env
  mlflow:
    build: . 
    container_name: mlflow_ui
    ports:
      - "5050:5000"
    volumes:
      - "./:/home/src"
    command: "/app/run_app.sh mlflow ui -h 0.0.0.0"