"""init_database

Revision ID: 00e448a242e3
Revises: 
Create Date: 2023-05-11 16:51:36.888681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e448a242e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin_id', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('close_time', sa.DateTime(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('quote_asset_volume', sa.Float(), nullable=True),
    sa.Column('number_of_trades', sa.Integer(), nullable=True),
    sa.Column('taker_buy_base_asset_volume', sa.Float(), nullable=True),
    sa.Column('taker_buy_quote_asset_volume', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kline')
    op.drop_table('coin')
    # ### end Alembic commands ###
